@extends('layout.front')
@section('header')
    @include('front.header')
@stop
@section('content')
    @include('front.barSocial')
    @include('front.about')
    @include('front.do')
    @include('front.code')
@stop